#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "Hey, the to pdx.shp is required for this to run"
    exit
fi

topojson -q 1e5 -p +b01001e1,+b02001e2,+b02001e3,+b02001e5,+b03002e1,+b02001e5,+b02001e6,+b02001e7 -o source/data/blockgroups.json $1
topojson -p -o source/data/pdx.json -- source/data/blockgroups.json source/data/neighborhoods.json /Users/justin/dev/me/data/portland-atlas/shp/water.shp
